- name: DeployUtilities
  hosts: init
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/var/lib/snapd/snap/bin"
    LD_LIBRARY_PATH: "{{ ansible_env.LD_LIBRARY_PATH | default('') }}:/lib64"
  tasks:
  - name: Ensure ingress, dns, dashboard, storage, registry, helm3 are enabled
    command: microk8s enable ingress dns:{{nameServer | default('8.8.8.8,8.8.4.4')}} dashboard storage registry:size={{registrySize | default('20Gi')}} helm3
  - name: Ensure cert-manager is deployed
    command: microk8s kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml
  - name: Describe user secret
    shell: microk8s kubectl -n kube-system describe secret $(microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
    register: user_secret
  - name: Ensure ~/manifests dir exists
    file:
      path: ~/manifests
      state: directory
  - name: Template dashboard ingress manifest
    template:
      src: manifests/dashboard_ingress.yaml.tmpl
      dest: ~/manifests/dashboard_ingress.yaml
  - name: Ensure ingress manifest is applied
    command: microk8s kubectl apply -f ~/manifests/dashboard_ingress.yaml
  - name: Display dashboard token line
    debug:
      msg: "{{user_secret.stdout_lines[-1]}}"

- name: Fix permissions
  hosts: all
  become: yes
  tags: 
    - persmissions
  environment:
    PATH: "{{ ansible_env.PATH }}:/var/lib/snapd/snap/bin"
    LD_LIBRARY_PATH: "{{ ansible_env.LD_LIBRARY_PATH | default('') }}:/lib64"
  tasks:
  - name: Ensure dirs created under /var/snap/microk8s/common/default-storage are writable by everyone
    ansible.posix.acl:
      path: /var/snap/microk8s/common/default-storage
      etype: group
      default: yes
      permissions: rwX
      state: present
  - name: Ensure dirs created under /var/snap/microk8s/common/default-storage are writable by everyone
    ansible.posix.acl:
      path: /var/snap/microk8s/common/default-storage
      etype: other
      default: yes
      permissions: rwX
      state: present
